on:
  push:
    branches:
      - master

name: Create PDF

jobs:
  build:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: build PDF
        uses: takahashim/review-pdf-generator-action@master
        
      - name: upload as Artifacts
        uses: takahashim/review-pdf-generator-action/upload-artifact@master
